spring.application.name=product
haru.security.oauth2.client-id=${KEYCLOAK_CLIENT_ID:haru-api}

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate

spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost/auth/realms/haru}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI:http://localhost/auth/realms/haru/protocol/openid-connect/certs}
spring.security.oauth2.resourceserver.jwt.audiences=${KEYCLOAK_AUDIENCE:haru-api}

springdoc.paths-to-match=/api/**
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.persist-authorization=false

server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never
server.error.include-exception=false
