package com.haru.product.product.infrastructure.persistence;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;

import org.junit.jupiter.api.Test;

class ProductSchemaMigrationTests {

	private static final Path MIGRATION_FILE = Path.of(
			"src", "main", "resources", "db", "migration",
			"V1__create_products_and_product_compositions.sql");

	@Test
	void createsIdentityPrimaryKeysAndCaseInsensitiveSkuUniqueness() throws IOException {
		String migration = normalizedMigration();

		assertThat(occurrencesOf(migration,
				"id bigint generated by default as identity primary key"))
				.isEqualTo(2);
		assertThat(migration).contains(
				"create unique index uk_products_sku_lower on products (lower(sku))");
	}

	@Test
	void restrictsCompositionForeignKeyDeletes() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"constraint fk_product_composition_parent foreign key (parent_product_id) "
						+ "references products(id) on delete restrict",
				"constraint fk_product_composition_component foreign key (component_product_id) "
						+ "references products(id) on delete restrict");
	}

	@Test
	void enforcesCompositionUniquenessAndDomainChecks() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"constraint uk_product_composition_parent_component "
						+ "unique ( parent_product_id, component_product_id )",
				"constraint ck_product_composition_not_self "
						+ "check ( parent_product_id <> component_product_id )",
				"constraint ck_product_composition_quantity_positive check ( quantity > 0 )");
	}

	@Test
	void indexesBothCompositionRelationships() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"create index idx_product_compositions_parent_product_id "
						+ "on product_compositions (parent_product_id)",
				"create index idx_product_compositions_component_product_id "
						+ "on product_compositions (component_product_id)");
	}

	private static String normalizedMigration() throws IOException {
		return Files.readString(MIGRATION_FILE)
				.toLowerCase(Locale.ROOT)
				.replaceAll("\\s+", " ")
				.trim();
	}

	private static long occurrencesOf(String text, String value) {
		return text.split(java.util.regex.Pattern.quote(value), -1).length - 1L;
	}
}
