package com.haru.product.production.infrastructure.persistence;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;

import org.junit.jupiter.api.Test;

class ProductionSchemaMigrationTests {

	private static final Path MIGRATION_FILE = Path.of(
			"src", "main", "resources", "db", "migration",
			"V3__create_production.sql");

	@Test
	void createsProductionTablesWithIdentityPrimaryKeys() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"create table production_orders",
				"create table production_consumptions",
				"create table produced_lots");
		assertThat(occurrencesOf(
				migration,
				"id bigint generated by default as identity primary key"))
				.isEqualTo(3);
	}

	@Test
	void definesProductionOrderStateQuantityAndVersion() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"quantity_to_produce numeric(19, 6) not null",
				"status varchar(30) not null",
				"version bigint not null default 0",
				"started_at timestamptz",
				"completed_at timestamptz",
				"constraint ck_production_order_quantity check (quantity_to_produce > 0)");
	}

	@Test
	void definesConsumptionTraceabilityAndPositiveQuantity() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"component_product_id bigint not null",
				"consumed_lot_id bigint not null",
				"consumed_quantity numeric(19, 6) not null",
				"measurement_unit varchar(40) not null",
				"constraint ck_production_consumption_quantity check (consumed_quantity > 0)");
	}

	@Test
	void definesSingleProducedLotPerOrderAndUniqueInventoryLotLink() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"produced_quantity numeric(19, 6) not null",
				"constraint uk_produced_lot_order unique (production_order_id)",
				"constraint uk_produced_lot_inventory_lot unique (inventory_lot_id)",
				"constraint ck_produced_lot_quantity check (produced_quantity > 0)");
	}

	@Test
	void restrictsDeletesAcrossEveryProductionForeignKey() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"constraint fk_production_order_product foreign key (product_id) "
						+ "references products(id) on delete restrict",
				"constraint fk_production_consumption_order foreign key (production_order_id) "
						+ "references production_orders(id) on delete restrict",
				"constraint fk_production_consumption_component foreign key (component_product_id) "
						+ "references products(id) on delete restrict",
				"constraint fk_production_consumption_lot foreign key (consumed_lot_id) "
						+ "references inventory_lots(id) on delete restrict",
				"constraint fk_produced_lot_order foreign key (production_order_id) "
						+ "references production_orders(id) on delete restrict",
				"constraint fk_produced_lot_inventory_lot foreign key (inventory_lot_id) "
						+ "references inventory_lots(id) on delete restrict");
	}

	@Test
	void createsOrderAndConsumptionLookupIndexes() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"create index idx_production_orders_product_status "
						+ "on production_orders (product_id, status)",
				"create index idx_production_consumptions_order_id "
						+ "on production_consumptions (production_order_id)",
				"create index idx_production_consumptions_component_product_id "
						+ "on production_consumptions (component_product_id)",
				"create index idx_production_consumptions_consumed_lot_id "
						+ "on production_consumptions (consumed_lot_id)");
	}

	private static String normalizedMigration() throws IOException {
		return Files.readString(MIGRATION_FILE)
				.toLowerCase(Locale.ROOT)
				.replaceAll("\\s+", " ")
				.trim();
	}

	private static long occurrencesOf(String text, String value) {
		return text.split(java.util.regex.Pattern.quote(value), -1).length - 1L;
	}
}
