CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    sku VARCHAR(60) NOT NULL,
    product_type VARCHAR(40) NOT NULL,
    default_measurement_unit VARCHAR(40) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uk_products_sku_lower
    ON products (LOWER(sku));

CREATE TABLE product_compositions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_product_id BIGINT NOT NULL,
    component_product_id BIGINT NOT NULL,
    quantity NUMERIC(19, 6) NOT NULL,
    measurement_unit VARCHAR(40) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_product_composition_parent
        FOREIGN KEY (parent_product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_product_composition_component
        FOREIGN KEY (component_product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_product_composition_parent_component
        UNIQUE (
            parent_product_id,
            component_product_id
        ),

    CONSTRAINT ck_product_composition_not_self
        CHECK (
            parent_product_id <> component_product_id
        ),

    CONSTRAINT ck_product_composition_quantity_positive
        CHECK (
            quantity > 0
        )
);

CREATE INDEX idx_product_compositions_parent_product_id
    ON product_compositions (parent_product_id);

CREATE INDEX idx_product_compositions_component_product_id
    ON product_compositions (component_product_id);
