CREATE TABLE inventory_lots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    lot_number VARCHAR(80) NOT NULL,
    manufacture_date DATE,
    expiration_date DATE,
    initial_quantity NUMERIC(19, 6) NOT NULL,
    available_quantity NUMERIC(19, 6) NOT NULL,
    unit_cost NUMERIC(19, 4) NOT NULL,
    status VARCHAR(30) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_inventory_lot_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_inventory_lot_product_number
        UNIQUE (product_id, lot_number),

    CONSTRAINT ck_inventory_lot_initial_quantity
        CHECK (initial_quantity > 0),

    CONSTRAINT ck_inventory_lot_available_quantity
        CHECK (available_quantity >= 0),

    CONSTRAINT ck_inventory_lot_unit_cost
        CHECK (unit_cost >= 0),

    CONSTRAINT ck_inventory_lot_dates
        CHECK (
            manufacture_date IS NULL
            OR expiration_date IS NULL
            OR expiration_date >= manufacture_date
        )
);

CREATE INDEX idx_inventory_lots_product_id
    ON inventory_lots (product_id);

CREATE INDEX idx_inventory_lots_product_expiration_id
    ON inventory_lots (product_id, expiration_date, id);

CREATE TABLE inventory_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_lot_id BIGINT NOT NULL,
    movement_type VARCHAR(40) NOT NULL,
    quantity NUMERIC(19, 6) NOT NULL,
    resulting_quantity NUMERIC(19, 6) NOT NULL,
    reference_type VARCHAR(60),
    reference_id BIGINT,
    description VARCHAR(500),
    occurred_at TIMESTAMPTZ NOT NULL,
    created_by VARCHAR(150),

    CONSTRAINT fk_inventory_movement_lot
        FOREIGN KEY (inventory_lot_id)
        REFERENCES inventory_lots(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_inventory_movement_quantity
        CHECK (quantity > 0),

    CONSTRAINT ck_inventory_movement_resulting_quantity
        CHECK (resulting_quantity >= 0)
);

CREATE INDEX idx_inventory_movements_lot_occurred_at
    ON inventory_movements (inventory_lot_id, occurred_at);

CREATE INDEX idx_inventory_movements_reference
    ON inventory_movements (reference_type, reference_id);
