CREATE TABLE production_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    quantity_to_produce NUMERIC(19, 6) NOT NULL,
    status VARCHAR(30) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,

    CONSTRAINT fk_production_order_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_production_order_quantity
        CHECK (quantity_to_produce > 0)
);

CREATE INDEX idx_production_orders_product_status
    ON production_orders (product_id, status);

CREATE TABLE production_consumptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id BIGINT NOT NULL,
    component_product_id BIGINT NOT NULL,
    consumed_lot_id BIGINT NOT NULL,
    consumed_quantity NUMERIC(19, 6) NOT NULL,
    measurement_unit VARCHAR(40) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_production_consumption_order
        FOREIGN KEY (production_order_id)
        REFERENCES production_orders(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_production_consumption_component
        FOREIGN KEY (component_product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_production_consumption_lot
        FOREIGN KEY (consumed_lot_id)
        REFERENCES inventory_lots(id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_production_consumption_quantity
        CHECK (consumed_quantity > 0)
);

CREATE INDEX idx_production_consumptions_order_id
    ON production_consumptions (production_order_id);

CREATE INDEX idx_production_consumptions_component_product_id
    ON production_consumptions (component_product_id);

CREATE INDEX idx_production_consumptions_consumed_lot_id
    ON production_consumptions (consumed_lot_id);

CREATE TABLE produced_lots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_order_id BIGINT NOT NULL,
    inventory_lot_id BIGINT NOT NULL,
    produced_quantity NUMERIC(19, 6) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_produced_lot_order
        FOREIGN KEY (production_order_id)
        REFERENCES production_orders(id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_produced_lot_inventory_lot
        FOREIGN KEY (inventory_lot_id)
        REFERENCES inventory_lots(id)
        ON DELETE RESTRICT,

    CONSTRAINT uk_produced_lot_order
        UNIQUE (production_order_id),

    CONSTRAINT uk_produced_lot_inventory_lot
        UNIQUE (inventory_lot_id),

    CONSTRAINT ck_produced_lot_quantity
        CHECK (produced_quantity > 0)
);
