package com.haru.product.inventory.infrastructure.persistence;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;

import org.junit.jupiter.api.Test;

class InventorySchemaMigrationTests {

	private static final Path MIGRATION_FILE = Path.of(
			"src", "main", "resources", "db", "migration",
			"V2__create_inventory.sql");

	@Test
	void createsInventoryTablesWithIdentityPrimaryKeys() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"create table inventory_lots",
				"create table inventory_movements");
		assertThat(occurrencesOf(
				migration,
				"id bigint generated by default as identity primary key"))
				.isEqualTo(2);
	}

	@Test
	void definesLotColumnsAndProductScopedLotNumberUniqueness() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"initial_quantity numeric(19, 6) not null",
				"available_quantity numeric(19, 6) not null",
				"unit_cost numeric(19, 4) not null",
				"version bigint not null default 0",
				"constraint uk_inventory_lot_product_number unique (product_id, lot_number)");
	}

	@Test
	void restrictsForeignKeyDeletesAndEnforcesLotChecks() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"constraint fk_inventory_lot_product foreign key (product_id) "
						+ "references products(id) on delete restrict",
				"constraint ck_inventory_lot_initial_quantity check (initial_quantity > 0)",
				"constraint ck_inventory_lot_available_quantity check (available_quantity >= 0)",
				"constraint ck_inventory_lot_unit_cost check (unit_cost >= 0)",
				"constraint ck_inventory_lot_dates check ( manufacture_date is null "
						+ "or expiration_date is null or expiration_date >= manufacture_date )");
	}

	@Test
	void definesImmutableMovementHistoryShapeAndChecks() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"movement_type varchar(40) not null",
				"quantity numeric(19, 6) not null",
				"resulting_quantity numeric(19, 6) not null",
				"constraint fk_inventory_movement_lot foreign key (inventory_lot_id) "
						+ "references inventory_lots(id) on delete restrict",
				"constraint ck_inventory_movement_quantity check (quantity > 0)",
				"constraint ck_inventory_movement_resulting_quantity check (resulting_quantity >= 0)");
	}

	@Test
	void createsLotLookupFefoAndMovementHistoryIndexes() throws IOException {
		String migration = normalizedMigration();

		assertThat(migration).contains(
				"create index idx_inventory_lots_product_id on inventory_lots (product_id)",
				"create index idx_inventory_lots_product_expiration_id "
						+ "on inventory_lots (product_id, expiration_date, id)",
				"create index idx_inventory_movements_lot_occurred_at "
						+ "on inventory_movements (inventory_lot_id, occurred_at)",
				"create index idx_inventory_movements_reference "
						+ "on inventory_movements (reference_type, reference_id)");
	}

	private static String normalizedMigration() throws IOException {
		return Files.readString(MIGRATION_FILE)
				.toLowerCase(Locale.ROOT)
				.replaceAll("\\s+", " ")
				.trim();
	}

	private static long occurrencesOf(String text, String value) {
		return text.split(java.util.regex.Pattern.quote(value), -1).length - 1L;
	}
}
